# Generated by Django 2.2 on 2020-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
